version: '3.8'

services:
  airflow-webserver:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  airflow-scheduler:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
  
  airflow-worker:
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false

  custom-database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hw2
    volumes:
      - dbvol:/var/lib/postgresql/data
    ports:
      - "3306:3306"

volumes:
  dbvol: